apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-service
  namespace: openshift-gitops
spec:
  project: default
  destination:
    namespace: devops-apps
    server: https://kubernetes.default.svc
  source:
    path: kubernetes_templates/deployment
    repoURL: git@github.com:rhiemer/devops-service.git
    targetRevision: develop