apiVersion: v1
kind: Secret
metadata:
  name: git-secret-app-devops-service
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhiemer/devops-service.git
  password: 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
  username: not-used