bases:
- ../../base
namespace: main
commonLabels:
  app: devops-service
images:
- name: devops-service
  newName: image-registry.openshift-image-registry.svc:5000/main/devops-service
  newTag: 1.0.24-SNAPSHOT-main-20220308-191308
patches:
- path: route.yaml
  target:
    kind: Route

