resources:
- ./components/deployment.yaml
- ./components/service.yaml
- ./components/route.yaml
namespace: devops-apps
commonLabels:
  app: java-deployment-template
images:
- name: devops-service
  newName: image-registry.openshift-image-registry.svc:5000/develop/devops-service
  newTag: 1.0.5-SNAPSHOT-main-20220306-011050

