bases:
- ../../base
namespace: develop
commonLabels:
  app: devops-service
images:
- name: devops-service
  newName: image-registry.openshift-image-registry.svc:5000/develop/devops-service
  newTag: 1.0.14-SNAPSHOT-develop-20220306-215132
patches:
- path: route.yaml
  target:
    kind: Route

