bases:
- ../../base
namespace: develop
commonLabels:
  app: devops-service
images:
- name: devops-service
  newName: image-registry.openshift-image-registry.svc:5000/develop/devops-service
  newTag: 1.0.5-SNAPSHOT-main-20220303-113115
patches:
- path: route.yaml
  target:
    kind: Route
